# ----
# Site

title: Ursula Graber
url: "https://www.ursulagraber.com/"
baseurl:
google_analytics_key:
newsletter_action: https://formspree.io/xdoeqzvk
contact_action: https://formspree.io/mgeajewy
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Ursula's Dance blog.
author:
  name: Ursula Graber
  email: me@ursulagraber.com
  twitter: # twitter username without the @ symbol
social:
  name: Ursula Graber
  links:
    - https://www.ursulagraber.com

# -----
# Build

timezone: Etc/UTC

redirects: true

#turn to true to show post with a future date
#future: true

paginate: 10
paginate_path: "/:num/"
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      push_sidebar_down: true
      print_stylesheet: true
      comments: true
      _options:
        content:
          width: 1560
          height: 2000
        featured_image:
          width: 1560
          height: 2000
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
      push_sidebar_down: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - Vimeo
  - RSS

_options:
  author_image:
    width: 400
    height: 400
